version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  webapp:
    image: interview-test.api
    container_name: webapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ConnectionStrings__DefaultConnection=Server=.;Database=InterviewTestDb;User=sa;Password=@Passw0rd;Trusted_Connection=True;TrustServerCertificate=true;
    depends_on:
      - sqlserver
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: Dockerfile